### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by gustavobrunoro** [MohdShamweel/JsonToForms#1]
Export data

How do I export the data form filled in json.

I checked that the onSubmitButtonClick method validates the information, but how do I save

**Comment by MohdShamweel** [comment]
Here are two ways that can be used, please refer:

        `//Combined Data
        JSONObject jsonObject = new JSONObject(DataValueHashMap.dataValueHashMap);
        Log.d("onSubmitButtonClick: ", jsonObject.toString());


        //If single value required for corresponding _id's
        for (Map.Entry<String, String> hashMap : DataValueHashMap.dataValueHashMap.entrySet()){
            String key = hashMap.getKey(); //  _id of the JSONOModel provided
            String value = hashMap.getValue(); //value entered for the corresponding _id
            Log.d(key, value);
        }`


Also, refer to the updated code:
[https://github.com/MohdShamweel/JsonToForms/blob/5d0b770642bb0d44964e5873860d1e0d45aa741a/app/src/main/java/com/shamweel/json2forms/MainActivity.java#L80]

**Comment by MohdShamweel** [comment]
> Export data
> 
> How do I export the data form filled in json.
> 
> I checked that the onSubmitButtonClick method validates the information, but how do I save

Here are two ways that can be used, please refer:

        `//Combined Data
        JSONObject jsonObject = new JSONObject(DataValueHashMap.dataValueHashMap);
        Log.d("onSubmitButtonClick: ", jsonObject.toString());


        //If single value required for corresponding _id's
        for (Map.Entry<String, String> hashMap : DataValueHashMap.dataValueHashMap.entrySet()){
            String key = hashMap.getKey(); //  _id of the JSONOModel provided
            String value = hashMap.getValue(); //value entered for the corresponding _id
            Log.d(key, value);
        }`


Also, refer to the updated code:
[Here](https://github.com/MohdShamweel/JsonToForms/blob/5d0b770642bb0d44964e5873860d1e0d45aa741a/app/src/main/java/com/shamweel/json2forms/MainActivity.java#L80)

**Comment by gustavobrunoro** [comment]
hi thanks a lot for the help.

Take advantage of the forecast to add new types of fields ..

no seriously interesting case has a group check box, Switch, RadioGroupRatings

**Comment by MohdShamweel** [comment]
Thanks, will consider this.
